name: Cache Node and NPM Dependencies
description: This action allows to cache both Node and NPM Dependencies based on the package-lock.json file.

inputs:
  node-version:
    description: NodeJS version to use
    default: 20.x
    required: true
  working-dir: 
    description: The working directory of the application
    default: .
    required: false
  target-env:
    description: '"dev" or "prod". Controls whether dev Dependencies are installed'
    default: dev
    required: false

runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Debug package-lock.json existence
      run: ls -l ${{ env.working-dir }}/package-lock.json
      shell: bash
    
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-dir }}/node_modules
        key: node-modules-${{ inputs.target-env }}-${{ hashFiles(format('{0}/package-lock.json', inputs.working-dir)) }}
      
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true' 
      run: ${{ inputs.target-env == 'dev' && 'npm ci' || 'npm ci --omit=dev' }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
    