name: 06 - Contexts
run-name: 06 - Contexts | DEBIG - ${{ inputs.debug }}

on: 
   #push:
   workflow_dispatch:
    inputs:
        debug:
            type: boolean
            default: false
env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

jobs: 
    echo-date:
        runs-on: ubuntu-latest
        env: 
            MY_JOB_VAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'
        steps: 
            - name: Display Information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: $${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                echo "Variable Value: ${{ vars.MY_VAR }}"
            - name: Print Env Variables
              env: 
                MY_OVERWRITTEN_VAR: 'step'
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwrittern env: ${{ env.MY_OVERWRITTEN_VAR }}"
                echo "Job Var: ${{env.MY_JOB_VAR }}"
            - name: Print Env Variables - step2
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo "Overwrittern env: ${{ env.MY_OVERWRITTEN_VAR }}"
    echo-date2:
        runs-on: ubuntu-latest
        steps:
            - name: Print Env Variables - from Echo date 2 job
              run: |
                echo "Workflow env: $MY_WORKFLOW_VAR
                echo "Overwrittern env: $MY_OVERWRITTEN_VAR
