name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs: 
        use-cache:
            description: Whether to execute cache step
            type: boolean
            default: true

jobs:
  build: 
    runs-on: ubuntu-latest
    