name: 15 - Working with Matricies

on: 
   workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [18.x, 20/x, 21.x]
                os: 
                    - ubuntu-latest
                    - windows-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version}}

            - name: Perform Test
              run: echo "Running test on ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
     
    