name: 15 - Working with Matricies

on: 
   workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os: 
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node-version: '16.x'
                    - os: ubuntu-latest
                      node-version: '21.x'
                      tag: experimental
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version}}

            - name: Fail if experimental
              if: matrix.tag == 'experimental'
              run: exit 1

            - name: Perform Test
              run: |
                  echo "Running test on ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                  sleep 10

            - name: Upload results
              run: echo "Uploading test results"

    include-example:
        runs-on: ubuntu-latest
        name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
        strategy:
            matrix:
                color: [red, yellow]
                shape: [triangle, pentagon]
                size: [small, large]
                include: 
                    - color: red
                      shape: square

    