name: 16 - Working with Environments
run-name: 16 - Working with Environment | env-${{ inputs.target-env }}

on: 
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging
    
jobs:
    echo:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}
        env:
            my-env-value: ${{ vars.MY_ENV_VALE || 'default value' }}
        steps:
            - name: Echo Vars
              run: |
                echo "Env Variable: ${{ env.my-env-value }}"