name: 17 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}

on: 
    workflow_dispatch:
        inputs:
            target-env:
                description: 'Which environment to target for dependency installatiion'
                type: choice
                options:
                    - dev
                    - prod

env:
    working-dir: 17-custom-actions/react-app

jobs:
  build: 
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ env.working-dir }}      
    steps:
        - uses: actions/checkout@v4

        - name: Setup Node and NPM dependencies
          uses: ./.github/actions/composite-cache-deps
          with:
            node-version: '20.x'
            working-dir: ${{ env.working-dir }}
            target-env: ${{ inputs.target-env }}
        
        - name: Test
          run: npm run test
        
        - name: Build
          run: npm run build
