name: 17 -2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS

on: 
    workflow_dispatch:


jobs:
  dependency-update: 
    runs-on: ubuntu-latest   
    steps:
        - uses: actions/checkout@v4

        - name: check for dependency update
          uses: ./.github/actions/js-dependency-update

